# Generated by Django 4.0.6 on 2022-08-10 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='imagen',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
